language: node_js
node_js:
    - node
cache:
  yarn: true
install:
  - mkdir public
  - cd ./frontend && yarn install && cd -
  - yarn build-client
  - rm -rf frontend
deploy:
  provider: cloudfoundry
  username: apikey
  password: $BX_IAM_ID
  api: https://api.eu-gb.cf.cloud.ibm.com
  organization: francis.powlesland1@ibm.com
  space: dev
  app_name: chattucino
  buildpack: https://github.com/cloudfoundry/nodejs-buildpack